# Nome do seu workflow
name: Deploy Next.js site to Pages

on:
  # Roda quando um push é feito para a branch `main`
  push:
    branches: ["main"]

  # Permite que você rode este workflow manualmente pela aba Actions
  workflow_dispatch:

# Define as permissões necessárias para o job de deploy
permissions:
  contents: read
  pages: write
  id-token: write

# Define o que acontece quando o workflow roda
jobs:
  # Job de build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Pasta que o 'npm run build' (com output: 'export') gera
          path: ./out

  # Job de deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
