# Nome do Workflow
name: Build and Deploy CRA to GitHub Pages

on:
  # Dispara o workflow em pushes para a branch 'main'
  push:
    branches: ["main"]
  # Permite que você rode manualmente pela aba Actions
  workflow_dispatch:

# Define as permissões que o workflow precisa
permissions:
  contents: read
  pages: write
  id-token: write

# Define o que acontece quando o workflow roda
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 1. Baixa o código da sua branch 'main'
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configura o ambiente Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Pode ser 18 ou 20
          cache: 'npm'

      # 3. Instala as dependências
      - name: Install dependencies
        run: npm ci

      # 4. Faz o build do site (lendo o package.json para usar o 'homepage')
      - name: Build
        run: npm run build

      # 5. Prepara os arquivos para o deploy
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 6. Envia os arquivos da pasta 'build' para o GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      # 7. Publica o site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
